### ISSUE TITLE
Bad practice when several texts translating

### ISSUE THREAD

**Issue by norbornen** [oatmealine/boteline#2]
```js
yt.translate(params.join(' '), { to: lang, format: 'plain' }).then(translated => {
    let translateEmbed = new Discord.RichEmbed().setDescription(translated);
})
```

Привет,
это не совсем корректный подход к переводу так как при склеивании нескольких фраз в одну строку `params.join(' ')` может измениться общий смысл получившейся фразы.

Правильнее будет передавать `params` как массив и в колбеке сделать `translated.join(' ')`

**Comment by oatmealine** [comment]
params - это не список фраз, а список слов от получённых сообщений: например, если входит такая комманда:

`m=atr 1 2 3 4 asdf asdf`

params будет равен

`['1', '2', '3', '4', 'asdf', 'asdf']`

Это скорее ошибка на моей стороне, и лучше было бы вместо этого пользоватся `msg.content.split(' ').slice(1).join(' ')`
